"""meditation library tables

Revision ID: 095a2704f227
Revises: a56dae1aa4a7
Create Date: 2022-12-19 13:20:48.999078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095a2704f227'
down_revision = 'a56dae1aa4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lib_med',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('mp3_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lib_med')
    # ### end Alembic commands ###
