"""add cat columns

Revision ID: 18d582182035
Revises: 6517c4e2837d
Create Date: 2023-02-02 14:30:58.273968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d582182035'
down_revision = '6517c4e2837d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cat_img_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('cat_img_url')
        batch_op.drop_column('cat_description')

    # ### end Alembic commands ###
