"""added sos_med1 relationship

Revision ID: 1b537bf709ce
Revises: a05bc3ddcd23
Create Date: 2023-01-27 18:44:16.429531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b537bf709ce'
down_revision = 'a05bc3ddcd23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sos_med1', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_sos_med1_lib_med'), 'lib_med', ['sos_med1'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_sos_med1_lib_med'), type_='foreignkey')
        batch_op.drop_column('sos_med1')

    # ### end Alembic commands ###
