"""new2

Revision ID: 21a8d84c6bff
Revises: aaa631e4930c
Create Date: 2023-01-15 13:27:46.292369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a8d84c6bff'
down_revision = 'aaa631e4930c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lib_med', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Float(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_lib_med_category_categories'), 'categories', ['category'], ['id'])
        batch_op.drop_column('length')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lib_med', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_lib_med_category_categories'), type_='foreignkey')
        batch_op.alter_column('category',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('time')

    # ### end Alembic commands ###
