"""3rd try add alt text columns

Revision ID: a647d818e2f9
Revises: 4ce7f40d858f
Create Date: 2023-02-11 12:59:04.684813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a647d818e2f9'
down_revision = '4ce7f40d858f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat_img_alt_text', sa.Text(), nullable=True))

    with op.batch_alter_table('lib_med', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_alt_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lib_med', schema=None) as batch_op:
        batch_op.drop_column('cover_alt_text')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('cat_img_alt_text')

    # ### end Alembic commands ###
